# fly.toml app configuration file generated for recipe-finder-pierreg-rails on 2023-11-19T16:02:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "recipe-finder-pierreg-rails"
primary_region = "cdg"
console_command = "/rails/bin/rails console"

[build]

[deploy]
  release_command = "./bin/rails db:prepare"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.status]
    port = 3001
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/up"
    protocol = "http"
    tls_skip_verify = false
    [checks.status.headers]
      X-Forwarded-Proto = "https"
