default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: recipe_finder_dev

test:
  <<: *default
  database: recipe_finder_test

production:
  <<: *default
  database: recipe_finder_prod
  host: recipe-finder-pierreg-mysql.internal
