default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: recipe_finder_dev

test:
  <<: *default
  database: recipe_finder_test

production:
  <<: *default
  database: recipe_finder_prod
